pset2/encyclopedia/urls.py
from django.urls import path

from . import views
app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.content, name="page"),
    path("random/", views.random, name="random"),
    path("search/", views.search, name="search"),
    path("create/", views.create, name="create"),
    path("edit/<str:title>", views.edit, name="edit")
]

pset2/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

pset2/encyclopedia/models.py
from django.db import models

# Create your models here.

pset2/encyclopedia/views.py
# Various imports from django
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from markdown2 import Markdown
from django import forms

# Imports for util functions, and random.choice

from . import util
from random import choice

# Creating a new class for the user to create a form
class CreateForm(forms.Form):
    title = forms.CharField(label='', widget=forms.TextInput(attrs={'id': 'title'}))
    textarea = forms.CharField(widget=forms.Textarea(attrs={'cols': '10'}),  label='')

# A new class for the user to edit forms 

class EditForms(forms.Form):
    textarea = forms.CharField(widget=forms.Textarea(attrs={'cols': '10'}),  label='')

# Index Page 

def index(request):
    """
    Displays a list of all the entries. 
    """
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

# Content Page(s)

def content(request, title):
    """
    Displays the content of a particular entry(page).
    """
    # If we don't find the entry, then we display the 404 page
    if util.get_entry(title) == None:
        return render(request, "encyclopedia/404.html", {
            "name": title,
             "word": "find"
        })

    # If we find the entry, then we convert the markdown to HTML, and display it.
    a = util.get_entry(title)
    converter = Markdown()
    html = converter.convert(a)
    #print(html)
    return render(request, "encyclopedia/page.html",{
        "title": title,
        "content": html
    })

def random(request):
    """
    Redirects to a random page. 
    """
    li = util.list_entries()
    f = choice(li)
    #print(f)
    return HttpResponseRedirect(f'/wiki/{f}')

def search(request):
    """
    Searches for an entry in the wiki. 
    """
    # GETting the request
    q = request.GET.get('q').strip()
    li = util.list_entries()
    f = []

    # We redirect user to the page immediately, if the entry matches a page 
    if q in li:
        return HttpResponseRedirect(reverse('encyclopedia:page', args=[q]))
    # It might be a substring - Even if it isn't, {% empty %} handles that

    for each in li:
        if q.lower() in each.lower():
            f+=[each]

    if len(f)==1:
        result = "result"

    else:
        result="results"

    # We render the HTML page, having access to the following variables

    return render(request, "encyclopedia/search.html",{
        "f": f,
        "number": len(f),
        "result": result
    })

def create(request):
    """
    Helps the user to create a new entry. 
    """
    
    # Checking if it is a POST request, if it is, then we get the cleaned data
    if request.method == "POST":
        form = CreateForm(request.POST)

        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["textarea"]

            # Saving the entry 
        
            if title.lower() not in [each.lower() for each in util.list_entries()]:
                util.save_entry(title, content)
                return HttpResponseRedirect(reverse("encyclopedia:page", args=[title]))

            else:
                return render(request, "encyclopedia/create.html",
                {
                "form": form,
                "title_exists": True
            })
        else:
            return render(request, "encyclopedia/create.html",
            {
                "form": form
            })
    else:
        return render(request, "encyclopedia/create.html",
        {
            "form": CreateForm()
        })

def edit(request, title):
    """
    Helps the user to edit an existing entry. 
    """
    if util.get_entry(title) == None:
        return render(request, "encyclopedia/404.html", 
        {
            "name" : title,
            "word" : "edit"
        })
    else:
        if request.method == "POST":
            form = EditForms(request.POST)
            if form.is_valid():
                # If the form is valid, then we will get the cleaned_data and update the entry
                content = form.cleaned_data["textarea"]
                util.save_entry(title, content)
                return HttpResponseRedirect(reverse("encyclopedia:page", args=[title]))
        content = util.get_entry(title)
        # Simulating a POST request to fill in, the best alternative is a hashmap
        data = {
            'title': title, 
            'textarea': content
        }
        # Render the page with the data pre-populated in the textarea(and title)
        return render(request, "encyclopedia/edit.html", {
            "form": EditForms(data),
            "title": title
        })

pset2/encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}
{% block title %}
    Create a Page!
{% endblock %}
{% block body %}
    <h4 style="margin-top:5px;">Create a Page!</h4>
    {% if title_exists %}
        <p style="margin-top:12px;color:red;font-style: italic;">Title already exists!</p>
    {% endif %}
    <form action="{% url 'encyclopedia:create' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <br>
        <br>
        <input type="submit" value="Create It!">
    </form>
{% endblock %}

pset2/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}
{% block title %}
    Edit - Wiki
{% endblock %}
{% block body %}
    <h4 style="margin-top:5px;">Edit a Page!</h4>
    <input type="text" value="{{ title }}" disabled>
    <form method="post" action="{% url 'encyclopedia:edit' title %}">
        {% csrf_token %}
        {{ form }}
        <br>
        <br>
        <input type="submit" value="Edit It!">
    </form>
{% endblock %}

pset2/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <a href="{% url 'encyclopedia:page' entry %}"><li>{{ entry }}</li></a>
        {% endfor %}
    </ul>

{% endblock %}

pset2/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="/search">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia" value="{{ encyclopedia.search }}">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">
                        Create New Page
                    </a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">
                        Random Page
                    </a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

pset2/encyclopedia/templates/encyclopedia/page.html
{% extends "encyclopedia/layout.html" %}
    {% block title %}
        Wiki: {{ title }}
    {% endblock %}
    {% block body %}
        {{ content|safe }}
        <br>
        <br>
        <a href="{% url 'encyclopedia:edit' title %}"><input type="button" value="Edit"></a>

    {% endblock %}

pset2/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}
{% block title %}
    Search 
{% endblock %}
{% block body %}
    <p style="color:gray; font-style: italic;font-size:15px;padding:10px;text-align: left;">Found {{ number }} {{ result }}.</p>
    <ul>
        {% for entry in f %}    
            <li><a href="{% url 'encyclopedia:page' entry %}">{{ entry }}</a></li>
        {% empty %}
            <li>Hmm, looks like that didn't bring up any great matches. Did you make a typo?</li>
        {% endfor %}
    </ul>
{% endblock %}